# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92500dc1efbb127fe634c7d1ffd589d4cf13e978562c6a8278a90162d8379b665b91271e6557a11f933c1835c691fbcbc60be13323d7442548ec57163d414272

test:
  secret_key_base: 6b9726353d669deb35387353e7509a88697b5fab5c4e1cf312e26415cc12c55a4dfffb55c706c878f1fa5a46ac735440280c546bb11b687bcbbbc0432a406ebc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
